---

- hosts: all 
  gather_facts: yes
  become: yes
  roles:
    - role: k3s_prereq
    - role: k3s_download
    

- hosts: master
  become: yes
  roles:
    - role: k3s_cluster/master

- hosts: workers
  become: yes
  roles:
    - role: k3s_cluster/workers

- hosts: u8
  gather_facts: yes
  become: yes
  roles:
    - role: cluster_addons
      when: ansible_host == hostvars[groups['workers'][0]]['ansible_host']