apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: i4kmodule
spec:
  source:
    registry:
      url: "docker.io/annuore/i4kmod:latest"
  pvc:
    accessModes:
      - ReadWriteOnce
