
--- 

- name: Download k0s binary for amd64
  get_url: 
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-amd64
    dest: "{{ k0s_binary_dest }}" 
    mode: 0755


# fix for bug in get_url  https://github.com/ansible/ansible/issues/64016 .Valid for Ansible 2.9, leads to file re-download at every run. Gotten from the official movd/k0s-ansible github
  # when: item == "x86_64" and not (distro_path.path + "/k0s-"+ k0s_version + "-amd64") is exists
  # with_items: "{{ ansible_facts.architecture }}"

  # https://github.com/k0sproject/k0s/releases/download/v1.26.3%2Bk0s.0/k0s-v1.26.3+k0s.0-amd64
# ---
# - name: Make dir for k0s distro
#   file:
#     path: k0s/distro
#     state: directory
#   register: distro_path

# - name: Download k0s binary for amd64
#   get_url: 
#     url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-amd64
#     destination: "{{ distro_path.path }}" 
# # fix for bug in get_url  https://github.com/ansible/ansible/issues/64016 .Valid for Ansible 2.9, leads to file re-download at every run. Gotten from the official movd/k0s-ansible github
#   when: item == "x86_64" and not (distro_path.path + "/k0s-"+ k0s_version + "-amd64") is exists
#   with_items: "{{ ansible_facts.architecture }}"

# # - name: Download k0s binary for arm64
# #   get_url:
# #     url:  https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-arm64
# #     dest: "{{ distro_path.path }}"
# #     when: item == "aarch64" and not (distro_path.path + "/k0s-"+ k0s_version + "-arm64") is exists
# #     with_items: "{{ ansible_facts.architecture }}"

# - name: Copy k0s binary to bin path for amd64
#   copy: 
#     src: "{{ distro_path.path }}/k0s-{{ k0s_version }}-amd-64"
#     dest: "{{ k0s_binary_dest }}"
#     mode: 0755
#   # when: ansible_facts.architecture == "x86_64" == "x86_64"

# # - name: Copy k0s binary to bin path for arm64
# #   copy: 
# #     src: "{{ distro_path.path }}/k0s-{{ k0s_version }}-amd-64"
# #     dest: "{{ k0s_binary_dest }}"
# #     mode: 0755
# #   when: ansible_facts.architecture == "aarch64"
