
--- 

- name: Download k0s binary
  get_url: 
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-amd64
    dest: "{{ k0s_binary_dest }}" 
    mode: 0755


