- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0750

- name: install k3s single node cluster 
  shell: |
    curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={v1.25.7+k3s1} INSTALL_K3S_EXEC="server --disable=traefik --disable=servicelb --tls-san=$(hostname -I | awk '{print $1}') --flannel-external-ip $(hostname -I | awk '{print $1}') --node-external-ip --kube-apiserver-arg=allow-privileged=true  --disable-cloud-controller" sh -s 

- name: include task to deploy kubevip 
  include_tasks: kubevip.yaml

- name: Enable and check K3s service
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Replace https://localhost:6443 by https://master-ip:6443
  command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ master_ip }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  # changed_when: true
        
- name: Copy config file to user home directory
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0500

- name: Copy sample deployment file to user's home
  template:
    src: "deploy.yaml.j2"
    dest: "~{{ ansible_user }}/deploy.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777

- name: Install helm
  unarchive:
    src: https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
    dest: /usr/local/bin
    extra_opts: "--strip-components=1"
    mode: 0755
    remote_src: true
  args:
    creates: /usr/local/bin/helm

- name: Install nginx ingress controller 
  command: helm install --kubeconfig ~{{ ansible_user }}/.kube/config my-release oci://ghcr.io/nginxinc/charts/nginx-ingress

- name: install pre-requisites for kubernetes module
  apt:
    name: 
    - python3-openshift
    - python3-kubernetes
    state: present
    
- name: include task to deploy rancher 
  include_tasks: rancher_server.yaml

