--- 
# Install cert-manager
# - name: get cert-manager url 
#   get_url:  
#     url: https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
#     dest: ~{{ ansible_user }}
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: 0777

- name: create cert-manager namespace 
  kubernetes.core.k8s:
    kubeconfig: ~{{ ansible_user }}/.kube/config
    state: present 
    api_version: v1
    kind: Namespace 
    name: cert-manager 

# - name: install cert-manager
#   kubernetes.core.k8s:
#     kubeconfig: ~{{ ansible_user }}/.kube/config
#     state: present 
#     src: ~{{ ansible_user }}/cert-manager.yaml
#     namespace: cert-manager
- name: add jetsatck cert-manager repo to helm 
  command: helm repo add --kubeconfig ~{{ ansible_user }}/.kube/config jetstack https://charts.jetstack.io

- name: install CRDs for certmanager 
  command: kubectl apply --kubeconfig ~{{ ansible_user }}/.kube/config -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml

- name: update local helm repo 
  command: helm repo update 

- name: install cert-manager helm chart 
  command: helm install --kubeconfig ~{{ ansible_user }}/.kube/config cert-manager jetstack/cert-manager \
            --namespace cert-manager \
            --create-namespace \
            --version v1.11.0  

- name: wait for cert-manager pods
  kubernetes.core.k8s_info:
    kubeconfig: ~{{ ansible_user }}/.kube/config
    kind: Pod 
    wait: yes 
    wait_sleep: 10
    wait_timeout: 90
    label_selectors: 
      - "app=cert-manager"

# Install Rancher Management Server 
- name: add repo 
  kubernetes.core.helm_repository: 
    repo_name: rancher-stable
    repo_url: https://releases.rancher.com/server-charts/stable
    kubeconfig_path:  "/home/{{ ansible_user }}/.kube/config"
    repo_state: present
    
- name: install rancher using helm 
  kubernetes.core.helm: 
    name: rancher 
    chart_ref: rancher-stable/rancher
    values:
      replicas: 2
      # hostname: 192.168.1.204.sslip.io
      ingress: 
        enabled: false 
    release_namespace: cattle-system
    create_namespace: true
    kubeconfig_path: "/home/{{ ansible_user }}/.kube/config"