---

- name: delete kubevirt operator and custom resource
  become: false  
  shell: | 
    export KUBECONFIG=/home/{{ ansible_user }}/.kube/config
    export RELEASE=$(curl https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt) 
    kubectl delete -n kubevirt kubevirt kubevirt --wait=true 
    kubectl delete apiservices v1.subresources.kubevirt.io # this needs to be deleted to avoid stuck terminating namespaces
    kubectl delete mutatingwebhookconfigurations virt-api-mutator
    kubectl delete validatingwebhookconfigurations virt-operator-validator
    kubectl delete validatingwebhookconfigurations virt-api-validator   
    kubectl delete -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml 

- name: remove libguestfs lib 
  apt: 
    package: libguestfs-tools
    state: absent 

- name: remove files and directories 
  file: 
    name: "{{ item }}"
    state: absent 
  with_items: 
    - /usr/local/bin/virtctl
    - /home/{{ ansible_user }}/vm.yaml
    - /home/{{ ansible_user }}/vmi.yaml
    - /home/{{ ansible_user }}/virtctl

