---
- hosts: master
  gather_facts: true
  become: yes
  tasks:
    - name: Check if the kubevirt namespace exists
      shell: kubectl --kubeconfig "{{ kubeconfig }}" get namespace kubevirt --ignore-not-found
      register: kubevirt_check
      ignore_errors: true 
    
- name: Install Kubevirt
  hosts: master
  gather_facts: true
  become: true
  roles:
    - role: install
      when: kubevirt_check.stdout == ''
  tags: install-kubevirt

- name: Create Virtual Machines
  hosts: master
  gather_facts: true
  become: false
  roles:
    - role: create-vms
  tags: create-vms

- name: Configure Virtual Machines
  hosts: vms
  # We do not gather_facts because we do not know yet if a vm is ready
  gather_facts: false
  become: false
  roles:
    - role: configure-vms
  tags: configure-vms
