---
- name: get metallb url 
  get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v0.13.9/config/manifests/metallb-native.yaml 
    dest: ~{{ ansible_user }}
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777
- name: install metallb 
  kubernetes.core.k8s:
    kubeconfig: ~{{ ansible_user }}/k0s-kubeconfig.yaml
    state: present 
    src: ~{{ ansible_user }}/metallb-native.yaml 
  register: metallb_pods
- name: wait for metallb pods
  kubernetes.core.k8s_info:
    kubeconfig: ~{{ ansible_user }}/k0s-kubeconfig.yaml
    kind: Pod 
    wait: yes 
    wait_sleep: 10
    wait_timeout: 90
    label_selectors: 
      - "app = metallb"
  register: wait 
- name: make metallb directory 
  file: 
    path: ~{{ ansible_user }}/metallb
    state: directory 
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777
  register: metallb_dir
- name: write config into metallb dir 
  shell: |
    cat <<EOF > ~{{ ansible_user }}/metallb/ipddr.yaml
    apiVersion: metallb.io/v1beta1
    kind: IPAddressPool
    metadata:
      name: metallb-pool
      namespace: metallb-system
    spec:
      addresses:
      - 192.168.1.0/24
- name: write advertise metallb into metallb dir 
  shell: | 
    cat <<EOF > ~{{ ansible_user }}/metallb/l2advert.yaml
    apiVersion: metallb.io/v1beta1
    kind: L2Advertisement
    metadata:
      name: l2advert
      namespace: metallb-system
    spec:
      ipAddressPools:
      - metallb-pool
- name: configure metallb 
  block:
  - name: apply the ip address pool   
    kubernetes.core.k8s:
      kubeconfig: ~{{ ansible_user }}/k0s-kubeconfig.yaml
      state: present 
      src: ~{{ ansible_user }}/metallb/ipddr.yaml
  - name: apply the layer 2 advertisement 
    kubernetes.core.k8s:
      kubeconfig: ~{{ ansible_user }}/k0s-kubeconfig.yaml
      state: present 
      src: ~{{ ansible_user }}/metallb/l2advert.yaml    
      

