---

- name: Disable k0s service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - k0scontroller
    - k0sworker

# - name: Umount k0s filesystems
#   include_tasks: umount_with_children.yaml
#   with_items:
#     - "{{ k0s_data_dir }}"
#     - "{{ k0s_libexec_dir }}"
#   loop_control:
#     loop_var: mounted_fs

- name: reset k0s
  become: true 
  shell: k0s reset

- name: Remove k0s Directories
  become: true
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ k0s_config_dir }}"
    - "{{ k0s_data_dir }}"
    - "{{ k0s_libexec_dir }}"
    - /var/lib/kubelet
    - "{{ systemd_dest }}/k0scontroller.service"
    - "{{ systemd_dest }}/k0sworker.service"
    - ~{{ ansible_user }}/metallb
    - ~{{ ansible_user}}/metallb-native.yaml
    - ~{{ ansible_user}}/install.yaml
    - ~{{ ansible_user}}/argocd.txt


- name: daemon_reload
  systemd:
    daemon_reload: yes