
# - name: Copy sample files for vmi
#   template:
#     src: "vmi.yaml.j2"
#     dest: "~{{ ansible_user }}/vmi.yaml"
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: 0755