
- name: install python3 
  become: yes
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

- name: install pre-requisites
  apt:
    name: 
    - python3-openshift
    - python3-kubernetes
    state: present

- name: Install nginx ingress controller 
  command: helm install --kubeconfig ~{{ ansible_user }}/.kube/config my-release oci://ghcr.io/nginxinc/charts/nginx-ingress
  
- name: Install argocd 
  include_tasks: argocd.yaml

- name: Install rancher management server 
  include_tasks: rancher_server.yaml

