
- name: install python3 
  become: yes
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

- name: install pre-requisites
  apt:
    name: 
    - python3-openshift
    - python3-kubernetes
    state: present

- name: Install argocd 
  include_tasks: argocd.yaml

- name: Install rancher management server 
  include_tasks: rancher_server.yaml

