
--- 

- name: kubectl | install kubectl localy
  get_url:
    url: "https://dl.k8s.io/release/v1.27.0/bin/linux/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: 0755
    owner: root
    group: root
    force: yes
- name: test kubectl 
  command: kubectl --help
  register: kubectl
- debug:  
    msg: "{{ kubectl }}"