
- name: install longhorn requirements
  apt: 
    update_cache: true 
    name: 
    - open-iscsi
    - nfs-common
    state: present 

# install longhorn
- name: add repo 
  kubernetes.core.helm_repository: 
    repo_name: longhorn
    repo_url: https://charts.longhorn.io
    repo_state: present
  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] 
  
- name: install longhorn using helm 
  kubernetes.core.helm: 
    name: longhorn 
    chart_ref: longhorn/longhorn
    chart_version: 1.5.1      
    release_namespace: longhorn-system
    create_namespace: true
    kubeconfig_path: "/home/{{ ansible_user }}/.kube/config"
    force: true
  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] 
  # failed_when: false

- name: make longhorn directory 
  file: 
    name: ~{{ ansible_user }}/longhorn
    state: directory
    owner: "{{ ansible_user }}"
    mode: 0777

- name: get sample pvc yaml file
  template: 
    src: "longhorn-vm-pvc.yaml.j2"
    dest: ~{{ ansible_user }}/longhorn/longhorn-vm-pvc.yaml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777
    

- name: get sample storageclass file from url
  get_url: 
    url: https://raw.githubusercontent.com/longhorn/longhorn/v1.5.1/examples/storageclass.yaml
    dest: ~{{ ansible_user }}/longhorn
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0777






























