---

- name: set deleting-confirmation-flag to true
  become: false  
  shell: | 
    export KUBECONFIG=$HOME/.kube/config
    kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag
    kubectl delete all -l volume=longhorn -A
    
- name: uninstall longhorn using helm 
  kubernetes.core.helm: 
    name: longhorn 
    release_state: absent 
    chart_ref: longhorn/longhorn
    chart_version: 1.5.1     
    release_namespace: longhorn-system
    create_namespace: true
    kubeconfig_path: "/home/{{ ansible_user }}/.kube/config"

- name: delete repo 
  kubernetes.core.helm_repository: 
    repo_name: longhorn
    repo_url: https://charts.longhorn.io
    kubeconfig_path: "/home/{{ ansible_user }}/.kube/config"
    repo_state: absent

- name: remove longhorn requirements 
  apt: 
    update_cache: true 
    name: 
    - open-iscsi
    - nfs-common
    state: absent  

- name: remove files and directories 
  file: 
    name: "{{ item }}"
    state: absent 
  with_items: 
    - ~{{ ansible_user }}/longhorn
    

