---

- name: set deleting-confirmation-flag to true
  become: false  
  shell: | 
    export KUBECONFIG=/home/{{ ansible_user}}/.kube/config
    kubectl -n longhorn-system patch -p '{"value": "true"}' --type=merge lhs deleting-confirmation-flag

# - name: Check deleting-confirmation-flag status
#   command: kubectl -n longhorn-system get lhs deleting-confirmation-flag -o jsonpath='{.value}'
#   register: flag_status
#   changed_when: False
#   environment:
#     KUBECONFIG: "{{ kubeconfig }}"
#   tags: lh

# - name: Set deleting-confirmation-flag to true
#   command: >
#     kubectl -n longhorn-system patch lhs deleting-confirmation-flag --patch '{"value": "true"}' --type=merge
#   when: flag_status.stdout != "true" 
#   environment:
#     KUBECONFIG: "{{ kubeconfig }}"
#   tags: lh

- name: Get all longhorn volumes
  command: kubectl get all -l volume=longhorn -A
  register: longhorn_volumes
  changed_when: False
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  tags: lh

- name: Delete all longhorn volumes
  command: kubectl delete all -l volume=longhorn -A
  when: "'No resources found' not in longhorn_volumes.stdout"
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  tags: lh

- name: uninstall longhorn using helm 
  kubernetes.core.helm: 
    name: longhorn 
    release_state: absent 
    chart_ref: longhorn/longhorn
    chart_version: 1.5.1     
    release_namespace: longhorn-system
    kubeconfig_path: "{{ kubeconfig }}"

- name: delete repo 
  kubernetes.core.helm_repository: 
    repo_name: longhorn
    repo_url: https://charts.longhorn.io
    repo_state: absent

- name: Delete k8s Namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: longhorn-system
    state: absent
    kubeconfig_path: "{{ kubeconfig }}"

- name: remove longhorn requirements 
  apt: 
    update_cache: true 
    name: 
    - open-iscsi
    - nfs-common
    state: absent  

- name: remove files and directories 
  file: 
    name: "{{ item }}"
    state: absent 
  with_items: 
    - /home/{{ ansible_user }}/longhorn
    

